version: '3'

services:
  php:
    build:
      context: ./docker/php
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./:/app
      - composer:/root/.composer/cache
    depends_on:
      - database
    networks:
      database:

###> doctrine/doctrine-bundle ###
  database:
    container_name: postgres
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: "app"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1212"
    volumes:
      - ./_docker/postgres:/var/lib/postgresql/data:rw
    networks:
      database:
###< doctrine/doctrine-bundle ###

volumes:
  composer:

networks:
  database:
